import { AuthUser, UserProfile, DiscoverProfile, MatchItem, MessageItem, BlockRecord, UserSettings, DiscoverFilters } from '../types.js';
const TOKEN_KEY='flatmate_plus_token';
export function getStoredToken(){return localStorage.getItem(TOKEN_KEY);} export function setStoredToken(token:string){localStorage.setItem(TOKEN_KEY,token);} export function clearStoredToken(){localStorage.removeItem(TOKEN_KEY);}
async function request<T>(endpoint:string,options:RequestInit={}):Promise<T>{const token=getStoredToken();const headers:Record<string,string>={'Content-Type':'application/json',...(options.headers as Record<string,string>||{})};if(token)headers.Authorization=`Bearer ${token}`;try{const res=await fetch(endpoint,{...options,headers});const data=await res.json();if(!res.ok)throw new Error(data.error||'Something went wrong. Please try again.');return data as T;}catch(err:any){if(err.message?.includes('Failed to fetch'))throw new Error("Couldn't reach the server. Please check your internet connection.");throw err;}}
export async function compressImageDataUrl(dataUrl:string,maxDimension=1600,quality=.78):Promise<string>{if(!dataUrl?.startsWith('data:image/'))return dataUrl;return new Promise(resolve=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,maxDimension/Math.max(img.naturalWidth,img.naturalHeight));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=c.getContext('2d');if(!ctx){resolve(dataUrl);return;}ctx.drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/webp',quality));};img.onerror=()=>resolve(dataUrl);img.src=dataUrl;});}
function addLivenessChallenge(dataUrl:string,challenge?:string){if(!challenge||!dataUrl.startsWith('data:'))return dataUrl;return dataUrl.replace(/^data:([^;]+);base64,/,`data:$1;challenge=${challenge};base64,`);}
export const api={
 async signup(payload:{email:string;password:string;name?:string}){const r=await request<{token:string;user:AuthUser}>('/api/auth/signup',{method:'POST',body:JSON.stringify(payload)});if(r.token)setStoredToken(r.token);return r;},
 async login(payload:{email:string;password:string}){const r=await request<{token:string;user:AuthUser}>('/api/auth/login',{method:'POST',body:JSON.stringify(payload)});if(r.token)setStoredToken(r.token);return r;},
 async googleAuth(payload:{email:string;name?:string;google_id?:string;photo_url?:string}){const r=await request<{token:string;user:AuthUser}>('/api/auth/google',{method:'POST',body:JSON.stringify(payload)});if(r.token)setStoredToken(r.token);return r;},
 async sendOtp(phone:string){return request('/api/auth/send-otp',{method:'POST',body:JSON.stringify({phone})});},async verifyOtp(phone:string,otp:string){return request('/api/auth/verify-otp',{method:'POST',body:JSON.stringify({phone,otp})});},async getMe(){return request('/api/auth/me');},
 async deleteAccount(confirmation:string){const r=await request('/api/auth/delete-account',{method:'DELETE',body:JSON.stringify({confirmation})});clearStoredToken();return r;},
 async verifyLiveness(payload:{photo_base64:string;mime_type:string;challenge?:string}){const compressed=await compressImageDataUrl(payload.photo_base64,1024,.72);const challenged=addLivenessChallenge(compressed,payload.challenge);return request<{success:boolean;passed:boolean;confidence:number;message:string}>('/api/verify/liveness',{method:'POST',body:JSON.stringify({...payload,photo_base64:challenged,mime_type:'image/webp'})});},
 async verifyFaceMatch(payload:{live_photo_base64?:string;profile_photo_base64:string;mime_type?:string}){const live=payload.live_photo_base64?await compressImageDataUrl(payload.live_photo_base64,1024,.72):undefined;const profile=await compressImageDataUrl(payload.profile_photo_base64,1600,.78);return request('/api/verify/face-match',{method:'POST',body:JSON.stringify({...payload,live_photo_base64:live,profile_photo_base64:profile,mime_type:'image/webp'})});},
 async updateIntent(intent:{has_house:boolean;looking_to_co_search:boolean;looking_for_vacancy:boolean}){return request<{profile:UserProfile}>('/api/profile/intent',{method:'PUT',body:JSON.stringify(intent)});},
 async updateProfile(updates:Partial<UserProfile>){return request<{profile:UserProfile}>('/api/profile',{method:'PUT',body:JSON.stringify(updates)});},
 async uploadPhoto(payload:{photo_base64:string;mime_type:string;caption?:string;is_main?:boolean}){const compressed=await compressImageDataUrl(payload.photo_base64,1600,.78);return request('/api/profile/upload-photo',{method:'POST',body:JSON.stringify({...payload,photo_base64:compressed,mime_type:'image/webp'})});},
 async uploadHousePhoto(payload:{photo_base64:string;mime_type:string;caption?:string}){const compressed=await compressImageDataUrl(payload.photo_base64,1600,.78);return request('/api/profile/upload-house-photo',{method:'POST',body:JSON.stringify({...payload,photo_base64:compressed,mime_type:'image/webp'})});},
 async reactivateDiscover(){return request('/api/profile/reactivate-discover',{method:'POST'});},
 async getDiscoverProfiles(filters?:DiscoverFilters){const params=new URLSearchParams();if(filters)Object.entries(filters).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!==''){if(Array.isArray(v)){if(v.length)params.append(k,v.join(','));}else params.append(k,String(v));}});const query=params.toString()?`?${params}`:'';return request(`/api/discover${query}`);},
 async swipe(target_user_id:string,action:'like'|'pass'){return request('/api/discover/swipe',{method:'POST',body:JSON.stringify({target_user_id,action})});},async getPassedProfiles(){return request('/api/discover/passed');},async undoPass(target_user_id:string){return request('/api/discover/undo-pass',{method:'POST',body:JSON.stringify({target_user_id})});},
 async getMatches(){return request('/api/matches');},async getMatchDetail(matchId:string){return request(`/api/matches/${matchId}`);},async sendMessage(matchId:string,content:string){return request(`/api/matches/${matchId}/messages`,{method:'POST',body:JSON.stringify({content})});},async markMessagesRead(matchId:string){return request(`/api/matches/${matchId}/read`,{method:'POST'});},async requestMovingIn(matchId:string){return request(`/api/matches/${matchId}/moving-in`,{method:'POST'});},
 async blockUser(target_user_id:string,reason?:string){return request('/api/users/block',{method:'POST',body:JSON.stringify({target_user_id,reason})});},async reportUser(target_user_id:string,reason:string,details?:string){return request('/api/users/report',{method:'POST',body:JSON.stringify({target_user_id,reason,details})});},async getBlockedUsers(){return request('/api/users/blocked');},async unblockUser(target_user_id:string){return request('/api/users/unblock',{method:'POST',body:JSON.stringify({target_user_id})});},async getSettings(){return request('/api/settings');},async updateSettings(settings:Partial<UserSettings>){return request('/api/settings',{method:'PUT',body:JSON.stringify(settings)});}
};
