import { db } from '../src/db/index.ts';
import { users, profiles, matches, messages, swipes, userSettings } from '../src/db/schema.ts';
import { UserProfile, MatchItem, MessageItem, UserSettings as UserSettingsType } from '../src/types.js';

export async function syncUserToPostgres(user:any){try{await db.insert(users).values({id:user.id,email:user.email,phone:user.phone||null,name:user.name||null,phoneVerified:!!user.phone_verified,emailVerified:!!user.email_verified,googleId:user.google_id||null,passwordHash:user.password_hash||null,authProvider:user.auth_provider||'local'}).onConflictDoUpdate({target:users.id,set:{email:user.email,phone:user.phone||null,name:user.name||null,phoneVerified:!!user.phone_verified,emailVerified:!!user.email_verified,googleId:user.google_id||null,passwordHash:user.password_hash||null,updatedAt:new Date()}});}catch(err){console.error('PostgreSQL syncUser error:',err);}}

export async function syncProfileToPostgres(p:UserProfile){try{await db.insert(profiles).values({id:p.id,userId:p.user_id,name:p.name,age:p.age,gender:p.gender,dob:p.date_of_birth||null,locality:p.locality,city:p.city||'Bangalore',rentMin:p.rent_min,rentMax:p.rent_max,foodPreference:p.food_preference,cleanliness:p.cleanliness,sleepSchedule:p.sleep_schedule,smoking:p.smoking,drinking:p.drinking,petsPreference:p.pets,guestPolicy:p.guests,occupation:p.work_schedule||null,bio:p.bio||null,mainPhoto:p.main_photo||p.photos?.[0]?.url||null,photos:p.photos||[],isVerified:!!p.is_verified,peaceSignVerified:!!p.liveness_verified,nonNegotiables:p.non_negotiables||[],hobbies:p.hobbies||[],languages:p.languages||[],prompts:p.prompts||[],housingIntent:p.housing_intent||{},houseDetails:p.house_details||null,profileData:p as any,onboardingComplete:!!p.is_profile_complete}).onConflictDoUpdate({target:profiles.userId,set:{name:p.name,age:p.age,gender:p.gender,dob:p.date_of_birth||null,locality:p.locality,city:p.city||'Bangalore',rentMin:p.rent_min,rentMax:p.rent_max,foodPreference:p.food_preference,cleanliness:p.cleanliness,sleepSchedule:p.sleep_schedule,smoking:p.smoking,drinking:p.drinking,petsPreference:p.pets,guestPolicy:p.guests,occupation:p.work_schedule||null,bio:p.bio||null,mainPhoto:p.main_photo||p.photos?.[0]?.url||null,photos:p.photos||[],isVerified:!!p.is_verified,peaceSignVerified:!!p.liveness_verified,nonNegotiables:p.non_negotiables||[],hobbies:p.hobbies||[],languages:p.languages||[],prompts:p.prompts||[],housingIntent:p.housing_intent||{},houseDetails:p.house_details||null,profileData:p as any,onboardingComplete:!!p.is_profile_complete,updatedAt:new Date()}});}catch(err){console.error('PostgreSQL syncProfile error:',err);}}

export async function syncMatchToPostgres(m:MatchItem){try{await db.insert(matches).values({id:m.id,userIds:m.user_ids,matchScore:m.match_score,matchBreakdown:m.match_breakdown||{},status:m.status||'matched',movingInRequestedBy:m.moving_in_requested_by||[]}).onConflictDoUpdate({target:matches.id,set:{userIds:m.user_ids,matchScore:m.match_score,matchBreakdown:m.match_breakdown||{},status:m.status||'matched',movingInRequestedBy:m.moving_in_requested_by||[],updatedAt:new Date()}});}catch(err){console.error('PostgreSQL syncMatch error:',err);}}
export async function syncMessageToPostgres(msg:MessageItem){try{await db.insert(messages).values({id:msg.id,matchId:msg.match_id,senderId:msg.sender_id,recipientId:msg.recipient_id,content:msg.content,read:!!msg.read}).onConflictDoUpdate({target:messages.id,set:{content:msg.content,read:!!msg.read}});}catch(err){console.error('PostgreSQL syncMessage error:',err);}}
export async function syncSwipeToPostgres(swipe:{id:string;user_id:string;target_user_id:string;action:'like'|'pass'}){try{await db.insert(swipes).values({id:swipe.id,swiperId:swipe.user_id,targetId:swipe.target_user_id,action:swipe.action}).onConflictDoUpdate({target:swipes.id,set:{action:swipe.action}});}catch(err){console.error('PostgreSQL syncSwipe error:',err);}}
export async function syncSettingsToPostgres(userId:string,s:UserSettingsType){try{await db.insert(userSettings).values({userId,newMessageBanner:s.new_message_banner??true,emailNotifications:s.email_notifications??true,privacyMode:s.privacy_mode??false}).onConflictDoUpdate({target:userSettings.userId,set:{newMessageBanner:s.new_message_banner??true,emailNotifications:s.email_notifications??true,privacyMode:s.privacy_mode??false,updatedAt:new Date()}});}catch(err){console.error('PostgreSQL syncSettings error:',err);}}
